#!/usr/bin/env node
/**
 * reseed_db_clean.js
 * Limpia por completo la base de datos (excepto usuarios) e importa
 * el archivo Excel de descargas: Sitios_Apagado_Bafi.xlsx
 */

const { Pool } = require('pg');
const XLSX = require('xlsx');
const path = require('path');
const fs = require('fs');

const pool = new Pool({
  host:     process.env.DB_HOST || 'localhost',
  port:     parseInt(process.env.DB_PORT || '5432'),
  database: process.env.DB_NAME || 'proyectosapp_db',
  user:     process.env.DB_USER || process.env.USER || 'fernandoaldao',
  password: process.env.DB_PASSWORD || '',
});

async function run() {
  const client = await pool.connect();
  try {
    console.log('🔄 Iniciando proceso de reseeding limpio...');
    await client.query('BEGIN');

    // 1. Limpieza de tablas (PostgreSQL) en cascada, excepto la tabla 'users'
    console.log('🧹 Vaciando tablas relacionales y de datos (excepto usuarios)...');
    await client.query(`
      TRUNCATE TABLE 
        audit_log, 
        photos, 
        apagado_bafi, 
        apagado_equipos, 
        datos_generales, 
        hallazgos, 
        plannings, 
        sites 
      CASCADE;
    `);
    console.log('✅ Base de datos limpiada con éxito.');

    // 2. Leer y parsear el Excel desde Descargas
    const excelPath = '/Users/fernandoaldao/Downloads/Sitios_Apagado_Bafi.xlsx';
    console.log(`\nexcel 📍 Leyendo archivo excel desde: ${excelPath}`);
    if (!fs.existsSync(excelPath)) {
      throw new Error(`No se encontró el archivo en la ruta: ${excelPath}`);
    }

    const workbook = XLSX.readFile(excelPath);
    const worksheet = workbook.Sheets[workbook.SheetNames[0]];
    const rawData = XLSX.utils.sheet_to_json(worksheet);
    console.log(`✅ Excel leido. Total filas encontradas: ${rawData.length}`);

    // 3. Mapear y procesar los sitios
    const mappedSites = rawData.map(row => {
      const item = {
        id: row.code,
        code: row.code,
        name: row.name,
        commune: row.commune || '',
        address: row.address || '',
        lat: Number(row.latitude) || 0,
        lng: Number(row.longitude) || 0,
        region: Number(row.region) || 13,
        estadoExcel: row.Estado || 'Sin asignar',
        proyecto: row.Proyecto || 'Apagado BAFI',
        apagadoBAFI: row['apagado BAFI'] === 'SI' ? 'SI' : 'NO'
      };
      return item;
    });

    // 4. Escribir archivos locales del frontend
    const sitesJsonPath = path.join(__dirname, '../src/data/sitesData.json');
    const sitesTsPath = path.join(__dirname, '../src/data/sitesData.ts');

    console.log('\n💾 Guardando archivos locales en el frontend...');
    fs.writeFileSync(sitesJsonPath, JSON.stringify(mappedSites, null, 2));
    console.log(`   → Guardado sitesData.json en: ${sitesJsonPath}`);

    const tsFileContent = `// Autogenerated from Sitios_Apagado_Bafi.xlsx\nexport const sitesData = ${JSON.stringify(mappedSites, null, 2)};\n`;
    fs.writeFileSync(sitesTsPath, tsFileContent);
    console.log(`   → Guardado sitesData.ts en: ${sitesTsPath}`);

    // 5. Insertar los nuevos sitios en PostgreSQL
    console.log(`\n🏗️  Insertando ${mappedSites.length} sitios en PostgreSQL...`);
    let count = 0;
    for (const s of mappedSites) {
      await client.query(
        `INSERT INTO sites (id, code, name, commune, address, latitude, longitude, region, estado_excel, proyecto, apagado_bafi)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
         ON CONFLICT (id) DO UPDATE SET
           name=$3, commune=$4, address=$5, latitude=$6, longitude=$7,
           region=$8, estado_excel=$9, proyecto=$10, apagado_bafi=$11`,
        [
          s.id, s.code, s.name,
          s.commune, s.address,
          s.lat, s.lng,
          s.region,
          s.estadoExcel,
          s.proyecto,
          s.apagadoBAFI === 'SI',
        ]
      );
      count++;
    }
    console.log(`✅ ${count} sitios insertados en la base de datos.`);

    await client.query('COMMIT');
    console.log('\n🎉 ¡Proceso completado exitosamente!');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('\n❌ Error durante el reseeding:', err.message);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

run();
